server:
  http_listen_port: 3200

distributor:
  receivers:
    otlp:
      protocols:
        http:
        grpc:

compactor:
  compaction:
    block_retention: 168h # General Tempo trace retention. Set for 7 days (168h)

metrics_generator:
  processor:
    service_graphs: # Enable Service Graph in Tempo
      peer_attributes:
        - peer.service
        - db.name
        - db.system
      enable_virtual_node_label: true
  registry:
    collection_interval: 15s
    external_labels:
      source: tempo
  storage:
    path: /tmp/tempo/generator/wal
    remote_write:
      - url: http://prometheus:9090/api/v1/write
        send_exemplars: true

storage:
  trace:
    backend: local                     # backend configuration to use
    wal:
      path: /tmp/tempo/wal             # where to store the wal locally
    local:
      path: /tmp/tempo/blocks

overrides:
  defaults:
    metrics_generator:
      processors: [service-graphs, span-metrics] # enables metrics generator